import { IAlmacenArticulo, ILocacion } from "@/interfaces/modules/IAlmacen.interface";
import { api_getAllAlmacenArticuloBylocacion, api_getOneLocacion } from "@/services/bodega.service";
import { useUserStore } from "@/store/user.store";
import { AxiosError } from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import {
    Button,
    Divider,
    Input,
    Loading,
    Modal,
    Select,
    Textarea,
} from "react-daisyui";
import { FaArrowLeft, FaEye } from "react-icons/fa";
import { FiPlus } from "react-icons/fi";
import { useQuery } from "react-query";
import { toast } from "react-toastify";


export default function Page() {

    const router = useRouter();
    const { jwt } = useUserStore();
    const locacionId = router.query.id as string;

    const [locacion, setLocacion] = useState<ILocacion>();

    //useQuery es similar a useEffect
    const { isLoading, error, data, refetch } = useQuery(
        "LocacionByID",
        () => api_getOneLocacion(jwt, locacionId),
        {
            enabled: locacionId !== undefined && locacion === undefined,
            onSuccess: (data) => {
                setLocacion(data.data.dataList[0]);
            },
            onError: (err: AxiosError) => {
                toast.error("Ocurrio un error al buscar la locación");
                return router.back();
            },
        }
    );

    const [almacenArticulo, setAlmacenArticulo] = useState<IAlmacenArticulo[]>([]);

    const fetchAlmacenArticulo = async () => {
        try {
            const response = await api_getAllAlmacenArticuloBylocacion(jwt, locacionId);
            setAlmacenArticulo(response.data.dataList)

        } catch (errors) {
            console.log(errors);
        }
    };

    useEffect(() => {
        fetchAlmacenArticulo();
    }, [])



    return (
        <>
            <Head>
                <title>{locacion ? `Locacion ${locacion.descripcion}` : `Locacion`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="w-full rounded-lg border shadow-md hover:shadow-xl transition duration-300 ease-in-out">
                <div className="flex flex-col bg-primary">
                    <div className="flex flex-row justify-between bg-primary px-6 py-4 rounded-t-lg">
                        <h3 className="text-large font-bold text-base-100 text-center">
                            Locacion
                        </h3>
                        <h3 className="text-large font-bold text-base-100 text-center">
                            Dirección
                        </h3>
                    </div>
                    <div>
                        <div className="flex flex-row justify-between bg-primary px-6 py-4  rounded-b-lg">
                            <h3 className="text-large font-bold text-base-100">
                                {locacion ? locacion?.descripcion?.toUpperCase() : ""}
                            </h3>
                            <h3 className="text-large font-bold text-base-100">
                                {locacion ? locacion?.direccion.toUpperCase() : ""}
                            </h3>
                        </div>
                    </div>
                </div>

                <div className="flex md:flex-row lg:flex-row flex-col-reverse justify-around items-center mt-4 md:mt-0 lg:mt-0">
                    <button type="button" className="btn btn-primary mt-2" onClick={() => router.back()}><FaArrowLeft />Volver</button>

                    <div
                        className={
                            isLoading ? "stats shadow skeleton m-2" : "stats shadow m-2"
                        }
                    >
                        <div className="stat">
                            <div className="stat-title">
                                {isLoading ? (
                                    <span style={{ color: "transparent" }}></span>
                                ) : (
                                    "Total artículos"
                                )}
                            </div>
                            <div className="stat-value text-center">
                                {isLoading ? (
                                    <span className="" style={{ color: "transparent" }}>
                                        0
                                    </span>
                                ) : (
                                    <span className="">{almacenArticulo.length}</span>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
                {!isLoading ? (
                    <>
                        <div className="overflow-x-auto mb-4">
                            <table className="table">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Nombre Artículo</th>
                                        <th>Descripción Artículo</th>
                                        <th>Cantidad Artículo</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {almacenArticulo.map((almacenArticulo, index) => (
                                        <tr className="hover">
                                            <th className="text-bold">{index + 1}</th>
                                            <td>{almacenArticulo.articulo.nombre}</td>
                                            <td>{almacenArticulo.articulo.descripcion}</td>
                                            <td>{almacenArticulo.cantidad}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>



                    </>
                ) : (
                    <div className="text-primary text-center mt-4">
                        <Loading size="lg" />
                    </div>
                )}
            </div>
        </>

    );
}
