import { useRouter } from "next/router";
import { useInfiniteQuery, useQuery } from "react-query";

import { useUserStore } from "../../../store/user.store";
import { AxiosError } from "axios"; // Importa AxiosError de axios
import Head from "next/head";
import React, { useCallback, useEffect, useRef, useState } from "react";
import IcentroCosto, {
  IcentroCosto_Bodega,
} from "../../../interfaces/modules/ICentroCosto.interface";
import {
  ICentroCosto,
  ITipoLocation,
  LocationFormValues,
} from "../../../interfaces/creation";
import { FiPlus } from "react-icons/fi";
import {
  Button,
  Collapse,
  Divider,
  Input,
  Modal,
  Select,
  Table,
  Textarea,
} from "react-daisyui";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { AlmacenFormValues } from "../../../interfaces/creation";
import { useForm, useFormContext } from "react-hook-form";
import { ItipoAlmacen } from "@/schemas/tipo_almacen.schema";
import { toast } from "react-toastify";
import {
  api_getAlmacen,
  api_getOneCentroCosto,
  api_postAlmacen,
  api_getTipoLocation,
  api_postLocation,
} from "@/services/bodega.service";
import { api_getTipoAlmacen } from "@/services/tipos.service";
import {
  IAlmacen,
  ILocacion,
} from "../../../interfaces/modules/IAlmacen.interface";
import { FaArchive, FaArrowLeft, FaEye, FaPencilAlt, FaPlus } from "react-icons/fa";
import { CiEdit } from "react-icons/ci";
import { SlEye } from "react-icons/sl";
import { FaPencil } from "react-icons/fa6";
import { useSearchParams } from "next/navigation";

export default function Page() {
  const router = useRouter();
  const idString = router.query.id as string; // Convertir a cadena

  useEffect (()=>{
    console.log( idString);
  },[idString]);
  
  const { jwt } = useUserStore();
  const [tipoAlmacen, setTipoAlmacen] = useState<ItipoAlmacen[]>([]);
  const [dataCentroCosto, setDataCentroCosto] = useState<IcentroCosto>();
  const { isLoading, error, data, refetch } = useQuery(
    "CCbyID",
    () => api_getOneCentroCosto(jwt, idString),
    {
      enabled: idString !== undefined,
      onSuccess: (data) => {
        if (data.data.dataList.length !== 1) {
          return router.back();
        }
        setDataCentroCosto(data.data.dataList[0]);
      },
      onError: (err: AxiosError) => {
        if ((err.response?.data as any)?.message === "ID no encontrado")
          return router.back();
      },
    }
  );

  const createBodega = () => {
    const bodegaData = {
      empresaId: dataCentroCosto?.empresaId,
      empresaName: dataCentroCosto?.empresa.razonSocial,
      centroCostoId: dataCentroCosto?.id,
      centroCostoName: dataCentroCosto?.nombre,
    };
    localStorage.setItem("BodegaNew", JSON.stringify(bodegaData));
    router.push("/bodega/crear");
  };
  const editBodega = (almacen: IcentroCosto_Bodega) => {
    const bodegaData = {
      empresaId: dataCentroCosto?.empresaId,
      empresaName: dataCentroCosto?.empresa.razonSocial,
      centroCostoId: dataCentroCosto?.id,
      centroCostoName: dataCentroCosto?.nombre,
      nombre: almacen.nombre,
      sigla: almacen.sigla,
      id: almacen.id,
      descripcion: almacen.descripcion,
    };
    localStorage.setItem("BodegaNew", JSON.stringify(bodegaData));
    router.push("/bodega/crear");
  };
  const getTipoAlmacen = async () => {
    try {
      const data = await api_getTipoAlmacen(jwt);
      setTipoAlmacen(data.data.dataList);
    } catch (error) {
      console.log(error);
    }
  };
  useEffect(() => {
    getTipoAlmacen();
  }, []);

  return (
    <div className="flex items-center justify-center lg:mx-48">
      <Head>
        <title>Centro de costo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!isLoading && (
        <div className="w-full rounded-lg border shadow-md hover:shadow-xl transition duration-300 ease-in-out container">
          <div className="flex flex-col">
            <div className="flex flex-row justify-between bg-primary text-primary-content px-6 py-4 rounded-t-lg items-center">
              <h3 className="text- md:text-lg font-bold text-left">
                {dataCentroCosto?.nombre?.toUpperCase()}
              </h3>
              <h3 className="text-sm md:text-lg font-extrabold ">
                {dataCentroCosto?.sigla
                  ? dataCentroCosto?.sigla.toUpperCase()
                  : "Siglas no informadas"}
              </h3>
            </div>
            <div></div>
          </div>
          <div className="flex flex-col-reverse  md:flex-row justify-around items-center md:justify-between">
            <div className="flex md:flex-row flex-col-reverse space-y-2">
              <button
                onClick={createBodega}
                className="my-2 mx-0 md:mx-2 btn btn-primary"
              >
                <FiPlus className="mr-2" />
                Crear bodega
              </button>
              <button
                onClick={() => router.push("/bodega/almacen/tipoalmacen")}
                className=" btn btn-primary  "
              >
                <FaArchive className="mr-2" /> Tipo de almacenes
              </button>
            </div>
            <div
              className={
                isLoading
                  ? "stats shadow skeleton m-2 mt-4 md:mt-0"
                  : "stats shadow m-2 mt-4 md:mt-0"
              }
            >
              <div className="stat mr-3 text-center">
                <div className="stat-title">
                  {isLoading ? (
                    <span style={{ color: "transparent" }}>asd</span>
                  ) : (
                    "Total Bodegas"
                  )}
                </div>
                <div className="stat-value ">
                  {isLoading ? (
                    <span style={{ color: "transparent" }}>0</span>
                  ) : (
                    dataCentroCosto?.bodegas.length
                  )}
                </div>
              </div>
            </div>
          </div>
          <div className="divider" />
          <div className="text-left ml-4 mb-4">
            <span className="font-bold text-lg">Lista de Bodegas</span>
          </div>
          {dataCentroCosto?.bodegas.map(
            (option: IcentroCosto_Bodega, index: number) => (
              <div key={index}>
                <BodegaList
                  key={index}
                  bodega={option}
                  index={index}
                  tipoalmacen={tipoAlmacen}
                  edit={editBodega}
                />
              </div>
            )
          )}
        </div>
      )}
    </div>
  );
}

function BodegaList({
  index,
  bodega,
  tipoalmacen,
  edit,
}: {
  index: number;
  bodega: IcentroCosto_Bodega;
  tipoalmacen: ItipoAlmacen[];
  edit: (almacen: IcentroCosto_Bodega) => void;
}) {
  const router = useRouter();

  const validationSchema = z.object({
    EmpresaId: z
      .string({
        required_error: "Campo inválido",
        invalid_type_error: "Campo inválido",
      })
      .default(bodega.empresaId),
    CentroCostoId: z
      .string({
        required_error: "Campo inválido",
        invalid_type_error: "Campo inválido",
      })
      .default(bodega.centroCostoId),
    BodegaId: z
      .string({
        required_error: "Campo inválido",
        invalid_type_error: "Campo inválido",
      })
      .default(bodega.id),
    Id: z
      .string({
        required_error: "Campo inválido",
        invalid_type_error: "Campo inválido",
      })
      .optional(),
    TipoAlmacenId: z.string({
      required_error: "Campo inválido",
      invalid_type_error: "Campo inválido",
    }),
    Codigo: z.number({
      required_error: "Campo inválido",
      invalid_type_error: "Campo inválido",
    }),
    Nombre: z
      .string({
        required_error: "Campo requerido",
        invalid_type_error: "Campo incorrecto",
      })
      .min(4, { message: "Campo incorrecto" }),
  });
  const methods = useForm<AlmacenFormValues>({
    resolver: zodResolver(validationSchema),
  });
  const {
    register,
    handleSubmit,
    reset,
    control,
    getValues,
    setValue,
    formState: { errors },
  } = methods;
  const { jwt } = useUserStore();
  const [page, setPage] = useState<number>(1);
  const [meta, setMeta] = useState<{ total: number; pages: number }>({
    total: 0,
    pages: 0,
  });
  const [almacen, setAlmacen] = useState<IAlmacen>({
    centroCostoId: "0",
    descripcion: "",
    bodegaId: "0",
    codigo: "0",
    empresaId: "0",
    id: "0",
    nombre: "0",
    tipoAlmacenId: "0",
  });
  const creationRef = useRef<HTMLDialogElement>(null);
  const handleShowCreation = useCallback(() => {
    creationRef.current?.showModal();
  }, [creationRef]);
  const handleCloseCreation = useCallback(() => {
    creationRef.current?.close();
  }, [creationRef]);

  const [isOpen, setIsOpen] = useState(false);

  const fetchAlmacen = async ({ pageParam = 1 }) => {
    const response = await api_getAlmacen(jwt, pageParam, bodega.id);
    return response.data;
  };
  const {
    data,
    error,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
    status,
    refetch,
    isLoading,
  } = useInfiniteQuery(`almacen-${bodega.id}`, fetchAlmacen, {
    getNextPageParam: (lastPage, pages) => {
      if (lastPage.pages > pages.length) {
        return pages.length + 1;
      } else {
        return undefined; // no more pages to load
      }
    },
    onSuccess: (data) => {
      const lastPage = data.pages[data.pages.length - 1];
      setMeta({
        total: lastPage.total,
        pages: lastPage.pages,
      });
    },
  });
  const AlmacenSubmit = async (data: AlmacenFormValues) => {
    try {
      await api_postAlmacen(jwt, data);
      if (data.Id) toast.success("¡El nuevo almacén se creo correctamente!");
      if (!data.Id) toast.success("¡Se modifico el almacén correctamente");
      refetch();
      reset();
      handleCloseCreation();
    } catch (error) {
      console.log(error);
    }
  };
  const editAlmacen = (almacen: IAlmacen) => {
    setValue("Id", almacen.id);
    setValue("TipoAlmacenId", almacen.tipoAlmacenId);
    setValue("Nombre", almacen.nombre);
    setValue("Codigo", almacen.codigo);
    handleShowCreation();
  };
  const ref = useRef<HTMLDialogElement>(null);
  const handleShow = useCallback(() => {
    ref.current?.showModal();
    /* setValue(); */
  }, [ref]);

  const allItems = data?.pages?.flatMap((page) => page.dataList) || [];

  // bodega
  return (
    <>
      <Collapse.Details tabIndex={index} open={isOpen} icon="arrow">
        <Collapse.Details.Title className="text-lg font-bold cursor-pointer border-b border-gray-200 pb-2">
          {bodega.nombre?.toUpperCase()}{" "}
          {bodega.sigla && `- ${bodega.sigla.toUpperCase()}`}
        </Collapse.Details.Title>
        <Collapse.Content className="p-4">
          {isLoading ? (
            <h1>Cargando</h1>
          ) : (
            <>
              <div className="text-left ml-2 mb-4">
                {allItems.length !== 0 && (
                  <span className="font-bold text-lg mb-2">
                    Lista de Almacenes
                  </span>
                )}
                {bodega.descripcion && bodega.descripcion.length !== 0 && (
                  <div className="flex flex-row justify-center mt-3">
                    <div className="rounded-3xl	bg-[#E0EFF2] border-2 border-[#8AE4F6] flex items-center flex-row md:pt-2  md:pr-6  md:pb-2 md:pl-4">
                      <div className="m-4">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-12 h-12 md:w-12 md:h-12"
                          viewBox="0 0 32 32"
                          fill="none"
                        >
                          <g clipPath="url(#clip0_200_2260)">
                            <path d="M0 0H32V32H0V0Z" fill="#E0EFF2" />
                            <path
                              d="M16.0001 2.66663C8.64008 2.66663 2.66675 8.63996 2.66675 16C2.66675 23.36 8.64008 29.3333 16.0001 29.3333C23.3601 29.3333 29.3334 23.36 29.3334 16C29.3334 8.63996 23.3601 2.66663 16.0001 2.66663ZM16.0001 22.6666C15.2667 22.6666 14.6667 22.0666 14.6667 21.3333V16C14.6667 15.2666 15.2667 14.6666 16.0001 14.6666C16.7334 14.6666 17.3334 15.2666 17.3334 16V21.3333C17.3334 22.0666 16.7334 22.6666 16.0001 22.6666ZM17.3334 12H14.6667V9.33329H17.3334V12Z"
                              fill="#6500E4"
                            />
                          </g>
                          <defs>
                            <clipPath id="clip0_200_2260">
                              <rect width="32" height="32" fill="white" />
                            </clipPath>
                          </defs>
                        </svg>
                      </div>
                      <span className=" mx-4 text-sm text-left md:text-base font-bold my-4 md:my-0">
                        {bodega.descripcion}
                      </span>
                    </div>
                  </div>
                )}
              </div>
              {allItems.length !== 0 ? (
                <>
                  <span className="font-bold text-lg mb-2">
                    Lista de Almacenes
                  </span>

                  {/* SM SCREEN */}
                  {data?.pages?.map((page, pageIndex) => (
                    <React.Fragment key={pageIndex}>
                      {page.dataList.map((almacen: IAlmacen, index: number) => (
                        <div
                          key={index}
                          className="md:hidden shadow my-2 border rounded-md  w-full shadow-md"
                        >
                          <div className="flex flex-row justify-between p-2">
                            <div className="basis-1/2 flex flex-col justify-left text-left">
                              <span className="font-bold mb-2">Nombre</span>
                              <span className="text-sm align-left">
                                {almacen.nombre?.toUpperCase()}
                              </span>
                            </div>
                            <div className="basis-1/2 flex flex-col justify-left text-right ">
                              <span className="font-bold mb-2">Tipo</span>
                              <span className="text-sm align-left">
                                {
                                  tipoalmacen.find(
                                    (e) => e.id === almacen.tipoAlmacenId
                                  )?.nombre
                                }
                              </span>
                            </div>
                          </div>
                          <div className="flex flex-row p-3 bg-[#FAF6FF] justify-between">
                            <span className="font-bold text-sm">Acciones</span>
                            <div className="flex space-x-4">
                              <a
                                onClick={() => editAlmacen(almacen)}
                                className="flex items-center"
                              >
                                <span className=" underline text-primary">
                                  Editar
                                </span>
                                <FaPencil className="text-primary ml-2" />
                              </a>
                              <a
                                onClick={() =>
                                  router.push(
                                    `/empresa/centrocosto/almacen/${almacen.id}`
                                  )
                                }
                                className="flex items-center"
                              >
                                <span className="underline text-primary">
                                  Ver
                                </span>
                                <FaEye className="text-primary ml-2" />
                              </a>
                            </div>
                          </div>
                        </div>
                      ))}
                    </React.Fragment>
                  ))}

                  {/* MD SCREEN */}
                  <Table
                    className="shadow border-collapse w-full responsive hidden md:table"
                    size="sm"
                  >
                    <thead className="bg-primary">
                      <tr>
                        <th className="text-base-100 font-extrabold">Codigo</th>
                        <th className="text-base-100 font-extrabold">
                          Nombre almacén
                        </th>
                        <th className="text-base-100 font-bold">
                          Tipo almacén
                        </th>
                        <th className="text-base-100 font-bold">Editar</th>
                        <th className="text-base-100 font-bold">Ver</th>
                      </tr>
                    </thead>
                    <tbody>
                      {data?.pages?.map((page, pageIndex) => (
                        <React.Fragment key={pageIndex}>
                          {page.dataList.map(
                            (almacen: IAlmacen, index: number) => (
                              <tr key={almacen.id}>
                                <td className="text-gray-700">
                                  {almacen.codigo}
                                </td>
                                <td className="text-gray-700">
                                  {almacen.nombre?.toUpperCase()}                                </td>
                                <td className="text-gray-700">
                                  {
                                    tipoalmacen.find(
                                      (e) => e.id === almacen.tipoAlmacenId
                                    )?.nombre
                                  }
                                </td>
                                <td>
                                      <button
                                        onClick={() => editAlmacen(almacen)}
                                        className="flex items-center justify-center w-8 h-8 rounded-full mr-2"
                                      >
                                        <CiEdit className="h-6 w-6 text-primary" />
                                      </button>
                                  <div
                                    className="tooltip mx-3"
                                    data-tip="Ubicaciones"
                                  >
                                    {/* <LocationList bodega={bodega} almacen={almacen}/> */}
                                  </div>
                                </td>
                                <td>
                                <button
                                        onClick={() =>
                                          router.push(
                                            `/empresa/centrocosto/almacen/${almacen.id}`
                                          )
                                        }
                                        className="flex items-center justify-center w-8 h-8 rounded-full"
                                      >
                                        <SlEye className="h-5 w-5 text-primary" />
                                      </button>
                                </td>
                              </tr>
                            )
                          )}
                        </React.Fragment>
                      ))}
                    </tbody>
                  </Table>

                  {/* NEXT PAGE BUTTON */}
                  <button
                    onClick={() => fetchNextPage()}
                    className="btn btn-primary rounded-full px-10 my-4"
                    disabled={!hasNextPage || isFetchingNextPage}
                  >
                    {isFetchingNextPage
                      ? "Cargando más..."
                      : hasNextPage
                      ? "Ver más"
                      : "No hay más datos"}
                  </button>
                </>
              ) : (
                <div className="flex flex-row justify-center mb-6">
                  <div className="rounded-3xl	bg-[#FFF9E1] border-2 border-[#FFE476] flex items-center flex-row md:pt-4  md:pr-6  md:pb-6 md:pl-4">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="w-24 h-24 md:w-12 md:h-12"
                      viewBox="0 0 32 32"
                      fill="none"
                    >
                      <path
                        d="M5.96 28H26.04C28.0933 28 29.3733 25.7734 28.3467 24L18.3067 6.65336C17.28 4.88003 14.72 4.88003 13.6933 6.65336L3.65333 24C2.62667 25.7734 3.90667 28 5.96 28ZM16 18.6667C15.2667 18.6667 14.6667 18.0667 14.6667 17.3334V14.6667C14.6667 13.9334 15.2667 13.3334 16 13.3334C16.7333 13.3334 17.3333 13.9334 17.3333 14.6667V17.3334C17.3333 18.0667 16.7333 18.6667 16 18.6667ZM17.3333 24H14.6667V21.3334H17.3333V24Z"
                        fill="#FF7E00"
                      />
                    </svg>
                    <span className=" mx-4 text-sm text-left md:text-base font-bold">
                      No existen Almacenes creados para esta Bodega
                    </span>
                  </div>
                </div>
              )}
              <div className="flex flex-col md:flex-row my-2">
                <div className="mt-2 md:mt-0 md:mr-2">
                  <button
                    onClick={() => {
                      reset();
                      handleShowCreation();
                    }}
                    className="btn btn-primary w-full md:w-auto"
                  >
                    <FiPlus className="mr-2" />
                    Crear Almacén
                  </button>
                </div>
                <div>
                  <button
                    onClick={() => edit(bodega)}
                    className="btn btn-link w-full md:w-auto mt-2 md:mt-0 md:ml-2"
                  >
                    <FaPencilAlt className="mr-2" />
                    Editar Bodega
                  </button>
                </div>
              </div>
            </>
          )}
        </Collapse.Content>
      </Collapse.Details>

      <Modal backdrop responsive ref={creationRef}>
        <Modal.Header className="font-bold">Almacén</Modal.Header>
        <Divider />
        <Modal.Body>
          <form
            onSubmit={handleSubmit((d) => AlmacenSubmit(d))}
            className="space-y-4"
          >
            <div className="flex flex-col">
              <label className="label">
                <span className="label-text">Nombre</span>
              </label>
              <Input
                color={errors.Nombre ? "error" : "neutral"}
                {...register("Nombre", {
                  setValueAs: (value) => (value === "" ? undefined : value),
                })}
              />
              {errors.Nombre && (
                <label className="label text-error">
                  {errors.Nombre.message}
                </label>
              )}
            </div>
            <div className="flex flex-col">
              <label className="label">
                <span className="label-text">Código</span>
              </label>
              <Input
                color={errors.Codigo ? "error" : "neutral"}
                {...register("Codigo", {
                  setValueAs: (value) =>
                    value === "" ? undefined : Number(value),
                })}
              />
              {errors.Codigo && (
                <label className="label text-error">
                  {errors.Codigo.message}
                </label>
              )}
            </div>
            <div className="flex flex-col">
              <label className="label">
                <span className="label-text">Tipo almacén</span>
              </label>
              <Select
                color={errors.TipoAlmacenId ? "error" : "neutral"}
                defaultValue={""}
                {...register("TipoAlmacenId", {
                  setValueAs: (value) => (value === "" ? undefined : value),
                })}
              >
                <Select.Option value="" disabled>
                  Seleccione el tipo de almacén
                </Select.Option>
                {tipoalmacen &&
                  tipoalmacen.map((almacen, index) => (
                    <Select.Option key={index} value={almacen.id}>
                      {almacen.nombre}
                    </Select.Option>
                  ))}
              </Select>
              {errors.TipoAlmacenId && (
                <label className="label text-error">
                  {errors.TipoAlmacenId.message}
                </label>
              )}
            </div>
            <div className="flex justify-center">
              <Button type="submit" color="primary">
                Guardar
              </Button>
            </div>
          </form>
        </Modal.Body>
      </Modal>
    </>
  );
}
