version: "3.9"

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    env_file:
      - .env       # ← Aquí cargas tu .env automáticamente
    environment:
      - NODE_ENV=production
    restart: unless-stopped
