import Head from "next/head";
import { useCallback, useEffect, useRef, useState } from "react";
import { Button, Divider, Input, Loading, Modal, Table } from "react-daisyui";
import { CiCirclePlus, CiEdit } from "react-icons/ci";
import { animated, useSpring } from "@react-spring/web";
import {
  ItipoAlmacen,
  ItipoAlmacenSchema,
  TipoAlmacenSchema,
} from "../../../schemas/tipo_almacen.schema";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import {
  api_getTipoAlmacen,
  api_postTipoAlmacen,
  api_putTipoAlmacen,
} from "../../../services/tipos.service";
import { useUserStore } from "../../../store/user.store";
import { toast, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function TipoAlmacen() {
  const [loading, setLoading] = useState<boolean>(false);
  const { jwt } = useUserStore();
  const [data, setData] = useState<ItipoAlmacen[]>([]);
  const [selectedElement, setSelectedElement] = useState<{
    id: string;
    action: "create" | "update";
  }>({ action: "create", id: "" });
  const [modalButton, setModalButton] = useState<boolean>(false);
  const getElement = async () => {
    try {
      setLoading(true);
      const data = await api_getTipoAlmacen(jwt);
      setData(data.data.dataList);
      setLoading(false);
    } catch (error) {
      console.log(error);
      setLoading(false);
    }
  };
  const newElement = async (data: ItipoAlmacenSchema | ItipoAlmacen) => {
    if (modalButton) return;
    try {
      console.log(selectedElement.action)
      setModalButton(true);
      if (selectedElement.action === "update") {
        await api_putTipoAlmacen(jwt, getValues());
        toast.success("¡El nuevo tipo de almacén se actualizo correctamente!");
      }
      if (selectedElement.action === "create") {
        await api_postTipoAlmacen(jwt, data);
        toast.success("¡El nuevo tipo de almacén se creo correctamente!");
      }
      reset();
      getElement();
      setModalButton(false);
      handleClose();

    } catch (error) {
      console.log(error);
    }
  };
  const ref = useRef<HTMLDialogElement>(null);
  const handleShow = useCallback(() => {
    ref.current?.showModal();
  }, [ref]);
  const handleClose = useCallback(() => {
    ref.current?.close();
  }, [ref]);

  useEffect(() => {
    getElement();
  }, []);

  const {
    register,
    handleSubmit,
    formState,
    reset,
    setValue,
    getValues,
    formState: { errors },
  } = useForm<ItipoAlmacenSchema>({
    resolver: zodResolver(TipoAlmacenSchema),
    mode: "onSubmit",
  });
  const editElement = (data: ItipoAlmacen) => {
    reset();
    const updatedElement = { ...selectedElement };
    updatedElement.action = "update";
    updatedElement.id = data.id;
    setSelectedElement(updatedElement);
    setValue("id", data.id);
    setValue("Codigo", data.codigo);
    setValue("Nombre", data.nombre);
    handleShow();
  };
  const createElement = () => {
    reset();
    const newElement = { ...selectedElement };
    newElement.action = "create";
    newElement.id = "";
    setSelectedElement(newElement);
    handleShow();
  };
  return (
    <>
      <Head>
        <title>Tipo de almacén</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-x-auto">
        {!loading ? (
          // listado almacen
          <Table className="w-full border-collapse shadow-md">
            <Table.Head className="bg-primary text-base-100">
              <span className="font-bold">No.</span>
              <span className="font-bold">Nombre</span>
              <span className="font-bold">Código</span>
              <span className="font-bold">Acciones</span>
            </Table.Head>
            <Table.Body>
              {data.map((item, index) => (
                <Table.Row key={index} className="hover:bg-gray-50">
                  <span className="text-gray-700">{index + 1}</span>
                  <span className="text-gray-700">{item.nombre}</span>
                  <span className="text-gray-700">{item.codigo}</span>
                  <span>
                    <button
                      onClick={() => editElement(item)}
                      className="p-2 rounded-full text-primary"
                    >
                      <CiEdit className="h-6 w-6" />
                    </button>
                  </span>
                </Table.Row>
              ))}
            </Table.Body>
            <Table.Footer>
              <span>
                
                <Button onClick={createElement} shape="circle" size="sm" className="bg-white shadow-none hover:none">
                  <CiCirclePlus className="h-6 w-6 text-primary" />
                </Button>
              </span>
              <span></span>
              <span></span>
              <span></span>
            </Table.Footer>
          </Table>


        ) : (
          <div className="flex justify-center items-center m-4">
            <Loading size="lg" color="primary" />
          </div>
        )}
      </div>

      {/* modal para crear o editar */}
      <Modal backdrop responsive ref={ref}>
        <Modal.Header className="font-bold">
          {selectedElement.action === "create"
            ? "Creación de nuevo Tipo de Almacén"
            : "Cambiar el Tipo de Almacén"}
        </Modal.Header>
        <Divider />
        <Modal.Body>
          <form onSubmit={handleSubmit((d) => newElement(d))} className="space-y-4">
            <div className="flex flex-col">
              <label className="label">
                <span className={`label-text ${errors.Codigo ? "text-error" : "text-blackl"}`}>Código</span>
              </label>
              <Input {...register("Codigo")} color={errors.Codigo ? "error" : "neutral"} className="input-primary" />
              {errors.Codigo && <label className="label"><span className="label-text-alt text-error">{errors.Codigo.message}</span></label>}
            </div>
            <div className="flex flex-col">
              <label className="label">
                <span className={`label-text ${errors.Nombre ? "text-error" : "text-black"}`}>Nombre</span>
              </label>
              <Input {...register("Nombre")} color={errors.Nombre ? "error" : "neutral"} className="input-primary" />
              {errors.Nombre && <label className="label"><span className="label-text-alt text-error">{errors.Nombre.message}</span></label>}
            </div>
            <div className="flex justify-center">
              <Button type="submit" color={errors.Codigo || errors.Nombre ? "error" : "primary"} className="btn-primary">
                {modalButton && <span className="loading loading-spinner text-white" />}
                <span className="ml-2">Guardar</span>
              </Button>
            </div>
          </form>
        </Modal.Body>
      </Modal>

    </>
  );
}
