import { useContextStore } from "@/store/context.store";
import { useUserStore } from "@/store/user.store";
import router from "next/router";
import { useCallback, useEffect, useState } from "react";
import {
  api_getAllAlmacenArticuloByEmpByCenByBodByAlm,
  api_getAllAlmacenByEmpByCenByBod,
  api_getEstadoArticulos,
  api_getOneEmpresa,
} from "../../../services/bodega.service";
import Head from "next/head";
import { IEmpresa } from "../../../interfaces/creation";
import { FaArrowLeft, FaSave } from "react-icons/fa";
import { FiPlus } from "react-icons/fi";
import { IAlmacen } from "../../../interfaces/modules/IAlmacen.interface";
import { Input, Loading } from "react-daisyui";
interface estadosI {
  codigo: number;
  nombre: string;
}
export default function Inventariar() {
  const { jwt } = useUserStore();
  const { empresa, bodega, centrocosto } = router.query as {
    empresa: string;
    bodega: string;
    centrocosto: string;
  };
  const [almacens, setAlmacens] = useState<any[]>([]);
  const { setActive } = useContextStore();
  useEffect(() => {
    setActive("Toma inventario");
  }, []);

  const getAlmacens = async () => {
    const alm = await api_getAllAlmacenByEmpByCenByBod(
      jwt,
      empresa,
      centrocosto,
      bodega
    );
    setAlmacens(alm.data.dataList);
  };
  const [estadosArticulos, setEstadosArticulos] = useState<estadosI[]>([]);

  const estadosArtGet = async () => {
    const estados = await api_getEstadoArticulos(jwt);
    setEstadosArticulos(estados.data.dataList);
  };
  useEffect(() => {
    if (!bodega) return;
    if (!empresa) return;
    getAlmacens();
    estadosArtGet();
  }, [router.query]);

  const [dataEmpresa, setDataEmpresa] = useState<IEmpresa>();

  useEffect(() => {
    const getOneEmpresa = async () => {
      if (empresa) {
        try {
          const data = await api_getOneEmpresa(jwt, empresa);
          setDataEmpresa(data.data.dataList[0]);
        } catch (error) {
          console.log(error);
        }
      }
    };
    getOneEmpresa();
  }, [jwt, empresa]);

  const [isLoading, setIsLoading] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>
          {dataEmpresa ? `Empresa ${dataEmpresa.razonSocial}` : `Empresa`}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full transition duration-300 ease-in-out">
        <div className="flex flex-col bg-primary bordered rounded-md shadow-md ">
          <div className="flex flex-row justify-between bg-primary px-6 py-4 rounded-md">
            <h3 className="text-large font-bold text-base-100">
              {dataEmpresa ? dataEmpresa?.razonSocial.toUpperCase() : ""}
            </h3>
            <h3 className="text-large font-bold text-base-100">
              {dataEmpresa ? dataEmpresa?.giro?.toUpperCase() : ""}
            </h3>
          </div>
        </div>

        <div className="flex md:flex-row lg:flex-row flex-col-reverse justify-start items-center mt-4 lg:mt-2">
          <button
            type="button"
            className="btn btn-primary"
            onClick={() => router.back()}
          >
            <FaArrowLeft />
            Volver
          </button>
        </div>

        {almacens ? (
          <>
            <div className="w-full grid grid-cols-1 gap-4">
              {almacens.map((e, index) => (
                <ViewAlmacen
                  key={index}
                  almacen={e}
                  empresa={empresa}
                  centrocosto={centrocosto}
                  bodega={bodega}
                  jwt={jwt}
                  estados={estadosArticulos}
                />
              ))}
            </div>
          </>
        ) : (
          <>
            <div className="text-primary text-center mt-4">
              <Loading size="lg" />
            </div>
          </>
        )}
      </div>
    </>
  );
}
interface IAllLocations {
  descripcion?: string;
  direccion: string;
  id: string;
}
interface IAllAlmacen {
  empresaId: string;
  bodegaId: string;
  id: string;
  tipoAlmacenId: string;
  codigo: string;
  nombre: string;
  descripcion: string;
  centroCostoId: string;
  locacions?: IAllLocations[];
}

interface props {
  almacen: IAllAlmacen;
  empresa: string;
  bodega: string;
  centrocosto: string;
  jwt: string;
  estados: estadosI[];
}
interface articuloI {
  articuloId: string;
  cantidad: number;
  locacion: string | undefined;
  nombre: string;
  descripcion: string;
  subfamilia: string;
  familia: string;
  estado: number;
  anoNumero: number;
}
function ViewAlmacen(props: props) {
  const [almacenArituclos, setAlmacenArticulos] = useState<articuloI[]>([]);

  const getArticles = async () => {
    const articles = await api_getAllAlmacenArticuloByEmpByCenByBodByAlm(
      props.jwt,
      props.empresa,
      props.centrocosto,
      props.bodega,
      props.almacen.id
    );

    const newElementsArticles: articuloI[] = [];
    articles.data.dataList.map((e: any) => {
      newElementsArticles.push({
        articuloId: e.articuloId,
        cantidad: e.cantidad,
        descripcion: e.articulo.descripcion,
        familia: e.articulo.subFamilium.familium.nombre,
        locacion: e.locacionId,
        nombre: e.articulo.nombre,
        subfamilia: e.articulo.subFamilium.nombre,
        estado: e.estadoArticuloCodigo,
        anoNumero: e.anoNumero,
      });
    });

    setAlmacenArticulos(newElementsArticles);
  };

  useEffect(() => {
    if (!props.empresa) return;
    if (!props.centrocosto) return;
    if (!props.bodega) return;
    if (!props.almacen) return;
    getArticles();
  }, [props.empresa, props.centrocosto, props.bodega, props.almacen]);

  return (
    <>
      <div className="flex flex-col bordered rounded shadow-md mt-2">
        <div className="flex flex-row justify-between bg-primary px-6 py-4 rounded-t-lg">
          <h3 className="text-large font-bold text-base-100 text-center">
            {props.almacen.nombre}
          </h3>
        </div>
        <div className="w-full grid grid-cols-1 gap-4 p-2">
          {props.almacen.locacions?.map(
            (locacion, index) =>
              almacenArituclos.filter((e) => e.locacion === locacion.id)
                .length !== 0 && (
                <ViewLocation
                  locacions={locacion}
                  articulos={almacenArituclos.filter(
                    (e) => e.locacion === locacion.id
                  )}
                  estados={props.estados}
                />
              )
          )}
        </div>
      </div>
    </>
  );
}

function ViewLocation(props: {
  locacions: IAllLocations;
  articulos: articuloI[];
  estados: estadosI[];
}) {
  return (
    <>
      <div className="flex flex-col bordered rounded shadow-md mt-2">
        <div className="flex flex-row justify-between bg-primary px-6 py-4 rounded-t-lg">
          <h3 className="text-large font-bold text-base-100 text-center">
            {props.locacions.direccion}
          </h3>
        </div>
        <div className="w-full grid grid-cols-1 gap-4 overflow-x-auto">
          <table className="table">
            {/* head */}
            <thead className="text-center">
              <tr>
                <th></th>
                <th>Nombre articulo</th>
                <th>Familia</th>
                <th>Cantidad en almacen</th>
                <th>Año</th>
                <th>Funcionario</th>
                <th>Persona Conteo</th>
                <th>Marca</th>
                <th>Estado</th>
                <th></th>
                <th></th>
                <th>Programa</th>
                <th></th>
              </tr>
            </thead>
            <tbody className="text-center">
              {props.articulos?.map((articulo, index) => (
                <tr className="hover">
                  <th>{index + 1}</th>
                  <td>{articulo.nombre}</td>
                  <td>
                    {articulo.familia}
                    <br />
                    {articulo.subfamilia}
                  </td>
                  <td className="font-bold">{articulo.cantidad}</td>
                  <td>{articulo.anoNumero}</td>
                  <td>
                    <select
                      defaultValue={""}
                      className="select border border-primary bg-white rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                    >
                      <option value={""} disabled selected>
                        Seleccione Fucionario
                      </option>
                      <option>jeje</option>
                      {/* {}se habre un modal para hacer un insert de una nueva marca */}
                    </select>
                  </td>
                  <td>
                    <select
                      defaultValue={""}
                      className="select border border-primary bg-white rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                    >
                      <option value={""} disabled selected>
                        Seleccione persona
                      </option>
                      <option>Otros</option>
                      {/* {}se habre un modal para hacer un insert de una nueva marca */}
                    </select>
                  </td>
                  <td>
                    <select
                      defaultValue={""}
                      className="select border border-primary bg-white rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                    >
                      <option value={""} disabled selected>
                        Seleccione Marca
                      </option>
                      <option> jejje</option>
                    </select>
                  </td>
                  <td>
                    <select
                      defaultValue={""}
                      className="select border border-primary bg-white rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                    >
                      <option value={""} disabled selected>
                        Seleccione Estado
                      </option>
                      <option> jejje</option>
                    </select>
                  </td>
                  <td>
                    <Input
                      type="text"
                      className="border border-primary bg-white rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                      placeholder="Lugar Fisico del Conteo"
                    />
                  </td>
                  <td>
                    <select
                      defaultValue={""}
                      className="select border border-primary bg-white rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                    >
                      <option value={""} disabled selected>
                        Seleccione Programa
                      </option>
                      <option> jejje</option>
                    </select>
                  </td>
                  <td>
                    <Input
                      type="text"
                      className="border border-primary bg-white rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                      placeholder="Presentacion"
                    />
                  </td>
                  <td>
                    <Input
                      type="text"
                      className="border border-primary bg-white rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                      placeholder="Observacion"
                    />
                  </td>
                  <td>
                    <Input
                      type="text"
                      className="border border-primary bg-white rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                      placeholder="Codigo"
                    />
                  </td>
                  <td>
                    <Input
                      type="number"
                      className="border border-primary bg-white rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                      placeholder="Numero de unidades"
                    />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="w-1/6 m-auto my-2">
          <button className="btn btn-outline btn-primary">
            <FaSave />
            Guardar
          </button>
        </div>
      </div>
    </>
  );
}
