import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  useForm,
  FormProvider,
  SubmitHandler,
  FieldValues,
} from "react-hook-form";
import React, { useCallback, useEffect, useRef } from "react";
import { Button, Modal } from "react-daisyui";
import { DiCode } from "react-icons/di";
import { useUserStore } from "@/store/user.store";
import { ArticuloFormValues } from "@/interfaces/creation";
import { api_postAlmacen } from "@/services/bodega.service";
import ArticuloId from "@/components/bodega/articulo/ArticuloId";
import ContentForm from "@/components/contentForm";
import ArticuloCodigo from "@/components/bodega/articulo/ArticuloCodigo";
import ArticuloInfo from "@/components/bodega/articulo/ArticuloInfo";
import { toast } from "react-toastify";
import { useRouter } from "next/router";





export default function CreateArticulo() {
  const { jwt } = useUserStore();
  const router = useRouter();

  const validationSchema = z.object({
    EmpresaId: z.string({ required_error: "Campo requerido1", invalid_type_error: "Campo requerido" }),
    AnoNumero: z.number({ required_error: "Campo requerido", invalid_type_error: "Campo requerido" }),
    SubFamiliaId: z.string({ required_error: "Campo requerido", invalid_type_error: "Campo requerido" }),
    Id: z.string({ required_error: "Campo requerido", invalid_type_error: "Campo requerido" }).optional(),
    TipoUnidadCodigo: z.number({ required_error: "Campo requerido", invalid_type_error: "Campo requerido" }),
    Codigo: z.string({ required_error: "Campo requerido", invalid_type_error: "Campo requerido" }).optional(),
    Nombre: z.string({ required_error: "Campo requerido", invalid_type_error: "Campo requerido" }),
    Descripcion: z.string({ required_error: "Campo requerido", invalid_type_error: "Campo requerido" }).optional(),
    Eliminado: z.boolean({ required_error: "Campo requerido", invalid_type_error: "Campo requerido" }).default(false)
  });
  const methods = useForm<ArticuloFormValues>({
    resolver: zodResolver(validationSchema),
  });
  const {
    setValue,
    control,
    formState: { errors },
  } = methods;

  //envio al formulario
  const onSubmit: SubmitHandler<FieldValues> = async (data) => {
    console.log(data)
    try {
      const save = await api_postAlmacen(jwt, data);

    } catch (error) {

    }
  };

  useEffect(() => {
    const loadDataArticulo = localStorage.getItem("articuloEmpresaId");
    if (loadDataArticulo && loadDataArticulo.length !== 0) {
      setValue("EmpresaId", loadDataArticulo);
    } else {
      toast.success("Empresa no encontrada");
      router.back();
    }
  }, []);


  return (
    <div className="m-2">
      <Head>
        <title>Artículos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button size="sm"><DiCode className="w-full h-full" /></Button>
      <FormProvider {...methods}>
        <form onSubmit={methods.handleSubmit(onSubmit)}>
          <ContentForm title="Datos Del Articulo">
            <ArticuloId errors={errors} />
            <ArticuloCodigo errors={errors} />
            <ArticuloInfo errors={errors} />

          </ContentForm>
          <div className="my-2">
            <div className="flex flex-wrap md:justify-end lg:justify-end justify-center mx-4">
              <Button color="primary">Guardar</Button>
            </div>
          </div>
        </form>
      </FormProvider>
    </div>
  );
}
